### ISSUE TITLE
Assignment 3: GUI system for each page (Discuss and assign On Friday10/28)

### ISSUE THREAD

**Issue by Keizo410** [Team-11-COSC-310/eLibrarian#19]
1, Navigation Screen for Login or Registration 
2, Registration Screen and Retry Screen
3, Login Screen and Retry Screen
__________________________________________________________________________________________________________________________
4, Navigation Screen for Main Menu(Login Succeed ver.)  and Main Menu (Default)
5, Book Search Screen
6, Booking Screen
7, Join Wait List Screen
_________________________________________________________________________________________________________________________________
8, Manage Account Screen (User info, Edit User Name, Delete Account, Check WaitList/Booking Status, Cancel WaitList/Booking)
9, Librarian Login Screen?
10, Manage Library (Add BooKs, Edit Books, Delete Books, Edit Userinfo, Delete UserAccount) Screens

Others.....

**Comment by Keizo410** [comment]
https://www.figma.com/file/RaXBs8LaWBFW6p9zJV5o8b/Untitled?node-id=0%3A1

**Comment by AdrianFWM** [comment]
https://www.figma.com/file/LJ9zhRTMokXTmoWRlz9wLS/Untitled-(Copy)?node-id=0%3A1&t=fluvEQ1vMaCFDe9V-1
Updated the admin page
